version: '3.3'

networks:
  hm-backend:

services:
  keycloak-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass_123
    command: mysqld --sql_mode=""
    networks:
      - hm-backend

  hivemaster-iam:
    image: hivemaster-iam
    depends_on:
      - keycloak-db
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    ports:
      - 8888:8888
      - 8090:8080
      - 8443:8443
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: db_user
      KC_DB_PASSWORD: db_pass_123
      KC_DB_URL_PROPERTIES: ?useSSL=false&allowPublicKeyRetrieval=true

      # Uncomment when in production
      KEYCLOAK_ADMIN: keycloak.admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak.admin

      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_FEATURES: token-exchange

      DEBUG_PORT: 8888
      PROXY_ADDRESS_FORWARDING: 'true'

      KC_LOG_CONSOLE_LEVEL: DEBUG
      KC_LOG_LEVEL: com.hivemaster:DEBUG,feign:DEBUG

      IAM_BASE_URL: http://192.168.1.8:8081
      IAM_BASE_PATH: /api/v1
    networks:
      - hm-backend
